# Generated by Django 5.1.5 on 2025-02-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20230801_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
